// Generated by gohack; DO NOT EDIT.
module github.com/dfang/auth

go 1.12

require (
	github.com/chanxuehong/internal v0.0.0-20180430074813-85d6017afbc4 // indirect
	github.com/chanxuehong/rand v0.0.0-20180830053958-4b3aff17f488
	github.com/chanxuehong/session v0.0.0-20141231161243-62053c2ee975
	github.com/chanxuehong/sid v0.0.0-20151130051504-1426da3b0352
	github.com/chanxuehong/wechat v0.0.0-20190521093015-fafb751f9916
	github.com/dfang/wechat-work-go v0.0.0-20190616111753-cbf0ed27ba02
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/google/go-github v17.0.0+incompatible
	github.com/google/go-querystring v1.0.0 // indirect
	github.com/gorilla/sessions v1.1.3 // indirect
	github.com/gosimple/slug v1.5.0 // indirect
	github.com/jinzhu/copier v0.0.0-20180308034124-7e38e58719c3
	github.com/jinzhu/gorm v1.9.8
	github.com/microcosm-cc/bluemonday v1.0.2 // indirect
	github.com/mrjones/oauth v0.0.0-20180629183705-f4e24b6d100c
	github.com/qor/assetfs v0.0.0-20170713023933-ff57fdc13a14 // indirect
	github.com/qor/mailer v0.0.0-20180329083248-0555e49f99ac
	github.com/qor/middlewares v0.0.0-20170822143614-781378b69454
	github.com/qor/qor v0.0.0-20190319081902-186b0237364b
	github.com/qor/redirect_back v0.0.0-20170907030740-b4161ed6f848
	github.com/qor/render v0.0.0-20171201033449-63566e46f01b
	github.com/qor/responder v0.0.0-20171031032654-b6def473574f
	github.com/qor/roles v0.0.0-20171127035124-d6375609fe3e
	github.com/qor/session v0.0.0-20170907035918-8206b0adab70
	github.com/rainycape/unidecode v0.0.0-20150907023854-cb7f23ec59be // indirect
	golang.org/x/crypto v0.0.0-20190325154230-a5d413f7728c
	golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
)
